spring:
  profiles:
    include: oauth
  sql:
    init:
      mode: always
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/testdb
##    url: jdbc:h2:mem:testdb;
#    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

    # 테이블 생성 후에 data.sql 실행

# jwt
jwt:
  issuer: dbsquddlfz@naver.com
  secret_key: study-springboot

