spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
#    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true
